### ISSUE TITLE
Ping Pong Game

### ISSUE THREAD

**Issue by SarthakSharma660** [KIET7UKE/Hacktoberfest-2K22#106]
i am currently working on a ping pong game using python may I add that here

**Comment by KIET7UKE** [comment]
Sure.

**Comment by SarthakSharma660** [comment]
@KIET7UKE hey i have made a pr please have a look

**Comment by KIET7UKE** [comment]
Merged :)

**Comment by SarthakSharma660** [comment]
@KIET7UKE thank you

**Comment by SarthakSharma660** [comment]
@KIET7UKE bro what happened to you repo ?
Why it is showing excluded on hacktober fest website?

**Comment by KIET7UKE** [comment]
Don't know bro, IG someone report it

**Comment by SarthakSharma660** [comment]
@KIET7UKE anything that we can do now ?

**Comment by KIET7UKE** [comment]
I have mailed Hacktoberfest team, will let you know

**Comment by SarthakSharma660** [comment]
@KIET7UKE any update from the team ?

**Comment by SarthakSharma660** [comment]
@KIET7UKE is there any update from hacktober fest team side ?

**Comment by KIET7UKE** [comment]
They are not accepting short codes, and only adding files & in my repository there is 100+ pr's on code addition and files addition. That's why they disqualified me as an maintainer but I can contribute to other repositories.

**Comment by SarthakSharma660** [comment]
@KIET7UKE can you please tell me in what all repos you are contributing?
