### ISSUE TITLE
this repo has been excluded from the hacktober fest!

### ISSUE THREAD

**Issue by Janhvi52** [KIET7UKE/Hacktoberfest-2K22#159]

**Comment by Harshvg2021** [comment]
How i check if a repository is valid for hacktoberfest or not ? Also how did u get to know?

**Comment by Janhvi52** [comment]
> How i check if a repository is valid for hacktoberfest or not ? Also how did u get to know?

I made a pr in this repo, then it showed me excluded in my hacktober profile
that's how I got to know!

**Comment by Harshvg2021** [comment]
Oh ok, thanks janhvi
