### ISSUE TITLE
Create a website using only HTML, CSS & JS.

### ISSUE THREAD

**Issue by KIET7UKE** [KIET7UKE/Hacktoberfest-2K22#18]
Create a website that contains all the JS projects displayed in an ordered box.
something like this,
![Screenshot (1071)](https://user-images.githubusercontent.com/76551267/193353330-72f2e07e-7a0d-4e41-8422-f6fc9f68d557.png)

**Comment by mehraankush** [comment]
what kind of js project.  can you plz elaborate

**Comment by KIET7UKE** [comment]
You can check it out in the readme file.

**Comment by mehraankush** [comment]
do i have to arrange them like the above picture .

**Comment by mehraankush** [comment]
if yes then assign it to me ..

**Comment by KIET7UKE** [comment]
yes & make a redirection link to the host website and leave it blank.

**Comment by KIET7UKE** [comment]
Assigned, go ahead and make a good contribution

**Comment by mehraankush** [comment]
yes of course thank you.

**Comment by Korak-Sengupta** [comment]
Can I add a calculator project to it?

**Comment by KIET7UKE** [comment]
@Korak-Sengupta yes you can.

**Comment by Geeky-Sam01** [comment]
@KIET7UKE Can I add Random Colour Generator to the project?

**Comment by KIET7UKE** [comment]
@Geeky-Sam01 Yes, It is beginners friendly repository. You can add any of your JS projects. Go for it

**Comment by harshkrt** [comment]
There's already some projects in Javascript folder. Do we need to submit different one?

**Comment by KIET7UKE** [comment]
@harshk-codes Yes, you can submit any other projects which are not listed here.

**Comment by harshkrt** [comment]
@KIET7UKE okay, thanks

**Comment by Korak-Sengupta** [comment]
Can you please tell the reason or the problem related with this?

Thanks
Korak Sengupta

**Comment by KIET7UKE** [comment]
@Korak-Sengupta Be specific on what you wanted to say.

**Comment by KIET7UKE** [comment]
@mehraankush any progress?

**Comment by Korak-Sengupta** [comment]
Sry, it got resolved, thank you.

**Comment by mehraankush** [comment]
@KIET7UKE  yeah i'm working on it

**Comment by KIET7UKE** [comment]
Any updates @mehraankush

**Comment by mehraankush** [comment]
can you explain which type of nav bar you wish for..

**Comment by KIET7UKE** [comment]
@mehraankush Any one of your choice.

**Comment by mehraankush** [comment]
any name you recommend for the web.

**Comment by KIET7UKE** [comment]
@mehraankush keep JS Projects

**Comment by KIET7UKE** [comment]
@mehraankush Hey, Why this is taking so long? Let me know if you having any issues.

**Comment by mehraankush** [comment]
haven't i made a PR alraedy ..

**Comment by KIET7UKE** [comment]
@mehraankush Yes, got it.
