### ISSUE TITLE
Create a website with a background video.

### ISSUE THREAD

**Issue by KIET7UKE** [KIET7UKE/Hacktoberfest-2K22#28]
You have to just create a simple website, listing some points for your reference, 
1. Keep it simple.
2. Add some CSS to looks good.
3. Having a background video.
4. Travelling or Scenic category will be the best fit for this website.

**Comment by TheInspiredConjurer** [comment]
Hey, please assign me this. I want to work on this.

**Comment by RAHUL14KUMAR** [comment]
hi i think i can solve this issue.
 i am a hacktoberfest 2022 paticipants. can u please assign this issue to me so that i can start working on it

**Comment by harshkrt** [comment]
hey can i work on this?

**Comment by harshk-codes** [comment]
hey can i work on this?

**Comment by KIET7UKE** [comment]
@TheInspiredConjurer Assigned to you. Looking forward to your valuable contribution.

**Comment by KIET7UKE** [comment]
@harshk-codes @RAHUL14KUMAR  you can work on some other issues. will add some more issues soon.

**Comment by TheInspiredConjurer** [comment]
Thanks a lot!

**Comment by KIET7UKE** [comment]
@TheInspiredConjurer Such an amazing work. Kudos to you. Thanks for contributing.
