### ISSUE TITLE
Create a React-Web-App.

### ISSUE THREAD

**Issue by KIET7UKE** [KIET7UKE/Hacktoberfest-2K22#34]
What the web app contains, 
1. First make a landing page containing 4-5blocks in a row.
       - Each block in a row will display a DSA Category problem(ex. Binary Search, Linear Search, Arrays, etc).
2. Once any of the boxes was selected, you have to redirect it to a new page containing a list of questions on that category.
3. Again make the final page that will display the code of that particular question.

Things you have to keep in mind, 
- Keep it simple,
- Add 5-10 Categories as well as Questions for beginner level,
- Adding a dark mode will be a +point.

**Comment by Alve2000** [comment]
@KIET7UKE  Hey, I would like to contribute to this project, Would appreciate it if you assign me.

**Comment by KIET7UKE** [comment]
@Alve2000 Okay, Assigning you.

**Comment by KIET7UKE** [comment]
@Alve2000 any updates?

**Comment by KumarRishabh22** [comment]
Can You plz assign me this issue, I am React-web-app developer

**Comment by KIET7UKE** [comment]
Assigning you as well @KumarRishabh22

**Comment by KIET7UKE** [comment]
@Alve2000  I have transferred your issue to https://github.com/KIET7UKE/Hacktoberfest2K22-2/issues/2
