### ISSUE TITLE
Linked List in C# 

### ISSUE THREAD

**Issue by SarthakSharma660** [KIET7UKE/Hacktoberfest-2K22#54]
I want to add a linked list using c# with all CRUD operations and read.md file explaining the concept of a linked list.

**Comment by KIET7UKE** [comment]
Sure, Go for it. Assigning you.

**Comment by SarthakSharma660** [comment]
@KIET7UKE 
okay I am working on it as soon as I am done I will update

**Comment by SarthakSharma660** [comment]
@KIET7UKE hey I have created a pr please have a look.

**Comment by KIET7UKE** [comment]
@SarthakSharma660 Merged :)

**Comment by HarshChhikara** [comment]
@KIET7UKE  There is no Read.md file here. Can I add that here?
