### ISSUE TITLE
Basic Snake Game using python

### ISSUE THREAD

**Issue by HarshChhikara** [KIET7UKE/Hacktoberfest-2K22#89]
@KIET7UKE 
Tried to replicate 90's snake game in python language. Can I add that?

**Comment by KIET7UKE** [comment]
Sure, go for it @HarshChhikara

**Comment by HarshChhikara** [comment]
@KIET7UKE I have raised the pr. kindly review it.

**Comment by KIET7UKE** [comment]
Yes, Merged.

**Comment by HarshChhikara** [comment]
it shows excluded on hacktoberfest website. any particular reason?
